name: CI
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  create:
    tags:
      - '*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: psf/black@22.1.0
      with:
        black_args: ". --check"
  pypi-release:
    needs: check
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') && github.repository_owner	== 'wpilibsuite'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dev-requirements.txt
      - name: Build PyPI Wheel
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
